apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-myapp
spec:
  destination:
    name: ''
    namespace: myapp
    server: 'https://kubernetes.default.svc'
  source:
    path: myapp
    repoURL: 'https://github.com/mollso/td2311-argocd-apps.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
