apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-myapp
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-myapp
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 4
          periodSeconds: 10
