apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-myapp
  name: go-myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-myapp
  template:
    metadata:
      labels:
        app: go-myapp
    spec:
      containers:
        - image: ghcr.io/ci7rix/go-myapp:latest
          name: go-myapp
          ports:
            - containerPort: 8080
          env:
            - name: POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
