apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-myapp
  name: go-myapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-myapp
  type: LoadBalancer
